spring:
  influx:
    url: http://localhost:8086
    token: my-super-secret-auth-token
    org: am_investment
    bucket: market_data


logging:
  level:
    root: INFO
    com.am.common.investment: DEBUG
